config/routes.rb
TheWallDevise::Application.routes.draw do
  get "comments/new"
  get "comments/create"
  devise_for :users
  resources :walls, only: [:index]
  resources :messages, only: [:new, :create]
  resources :comments, only: [:new, :create]

  root to: 'walls#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :message

	validates :content,
		presence: true,
		length: {minimum: 10}
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	
	validates :content, 
		presence: true,
		length: {minimum: 4}
end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
	end

	def create
		@comment = Message.find(params[:comment][:message_id]).comments.new(comment_params)
		@comment.user = User.find(current_user.id)
		if @comment.save
			redirect_to walls_path, notice: "Comment was successfully created."
		else
			render action: "walls#index"
		end
	end

	private
		def set_comment
			@comment = Comment.find(params[:id])
		end

		def comment_params
			params.require(:comment).permit(:content)
		end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def new
	end

	def create
		@message = User.find(current_user.id).messages.new(message_params)
		if @message.save
			redirect_to walls_path, notice: "Message was successfully created."
		else
			render action: "wall#index"
		end
	end

	private
		def set_message
			@message = Message.find(params[:id])
		end

		def message_params
			params.require(:message).permit(:content)
		end
end

app/controllers/walls_controller.rb
class WallsController < ApplicationController
  def index
  	@message = Message.new
  	@comment = Comment.new

  	@users = User.all
  	@messages = Message.all.order(created_at: :desc)
  	@comments = Comment.all.order(created_at: :asc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/walls_helper.rb
module WallsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= yield :header %>
	<%= yield %>

</body>
</html>

app/views/layouts/walls.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield :title %></title>
  <%= stylesheet_link_tag    "walls", media: "all" %>
  <%= javascript_include_tag "walls" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<div class="masthead">
			<%= yield :header %>
		</div>
	    <div class="row">
			<%= yield :body %>
		</div>
	</div>
</body>
</html>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/messages/new.html.erb
<h1>Messages#new</h1>
<p>Find me in app/views/messages/new.html.erb</p>

app/views/walls/index.html.erb
<% content_for :title do %>
	The Wall
<% end %>

<% content_for :header do %>
	<h4>The Wall</h4>
	<div id="user_nav">
		<% if user_signed_in? %>
			<p>Logged in as: <%= current_user.email %></p>
			<%= button_to 'Logout', destroy_user_session_path, class: "btn btn-danger btn-xs", method: :delete %>
		<% else %>
			<%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btn-xs" %>
			<%= link_to 'Login', new_user_session_path, class: "btn btn-primary btn-xs" %>
		<% end %>
	</div>
<% end %>

<% content_for :body do %>
	<div id="content" class="col-md-10">
		<% if user_signed_in? %>
			<h4>Post a message</h4>
			<%= simple_form_for @message, url: messages_path, html: {class: 'form'} do |f| %>
				<%= f.input :content, as: :text, label: false %>
				<%= f.submit "Post a message", class: 'btn btn-xs btn-primary' %>
			<% end %>
		<% end %>

		<% @messages.each do |message| %>
			<% user = @users.find(message.user_id) %>
			<h5 class="bold"><%= user.email %> - <%= message.created_at.strftime('%B %d, %Y') %></h5>
			<p><%= message.content %></p>

			<div class="comments">
				<% message.comments.all.each do |comment| %>
					<% user = comment.user %>
					<h5 class="bold"><%= user.email %> - <%= comment.created_at.strftime('%B %d, %Y') %></h5>
					<p><%= comment.content %></p>
				<% end %>
				
				<% if user_signed_in? %>
					<h6 class="bold">Post a comment</h6>
					<%= simple_form_for @comment, url: comments_path, html: {class: 'form'} do |f| %>
						<%= f.input :message_id, as: :hidden, input_html: { value: message.id } %>
						<%= f.input :content, as: :text, label: false %>
						<%= f.submit "Post a comment", class: 'btn btn-xs btn-success' %>
					<% end %>
				<% end %>
		<% end %>
<% end %>